[build]
xargo = false
build-std = false
default-target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
image = "idhyt/cross-rs-x86_64-unknown-linux-musl:0.2.5"

[target.aarch64-unknown-linux-musl]
image = "idhyt/cross-rs-aarch64-unknown-linux-musl:0.0.1"

[target.x86_64-apple-darwin]
image = "idhyt/cross-rs-x86_64-apple-darwin:1.88.0"

[target.aarch64-apple-darwin]
image = "idhyt/cross-rs-aarch64-apple-darwin:1.88.0"
# [target.aarch64-apple-darwin.env]
# RANLIB = "/usr/local/osxcross/target/bin/aarch64-apple-darwin23.5-ranlib"

[target.x86_64-pc-windows-gnu]
image = "idhyt/cross-rs-x86_64-pc-windows-gnu:1.88.0"
