/* automatically generated by rust-bindgen 0.69.4 */
#[cfg(target_family = "unix")]
extern "C" {
    pub fn passh(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
// extern "C" {
//     pub fn ssh_connect_shell(
//         user: *const ::std::os::raw::c_char,
//         password: *const ::std::os::raw::c_char,
//         host: *const ::std::os::raw::c_char,
//         port: ::std::os::raw::c_int,
//     ) -> ::std::os::raw::c_int;
// }
