[package]
name = "atsh-lib"
version = "0.1.6"
edition = "2021"
authors = ["idhyt3r@gmail.com"]
license = "MIT"
description = "autossh/@shell library is used to ssh login and allow automatically login without password"
readme = "README.md"
homepage = "https://github.com/idhyt/autossh/tree/main/atsh-lib"
repository = "https://github.com/idhyt/autossh/tree/main/atsh-lib"
keywords = ["atsh", "autossh", "atshell", "ssh", "passwordless"]
categories = [
    "network-programming",
    "command-line-utilities",
    "development-tools",
]

[lib]
name = "atsh_lib"
path = "src/lib.rs"

[dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
parking_lot = "0.12.5"
prettytable = "0.10.0"
rusqlite = { version = "0.39.0", features = ["bundled"] }
russh = { version = "0.60.2", default-features = false, features = ["ring"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["process"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "json",
    "local-time",
] }
# # cargo build --release --target x86_64-unknown-linux-musl --features openssl
# [target.'cfg(unix)'.dependencies]
# openssl = { version = "0.10.79", features = ["vendored"] }
